### ISSUE TITLE
Pixelated Loading GIF

### ISSUE THREAD

**Issue by kiwiProgrammer** [cs3216-quake/hawker-hub#36]
Loading GIF is pixelated

**Comment by andhieka** [comment]
![food_loading 2x](https://cloud.githubusercontent.com/assets/6689743/9648499/f786ae56-521b-11e5-8569-93312d1bfcd1.gif)
for retina

**Comment by andhieka** [comment]
![food_loading 1x](https://cloud.githubusercontent.com/assets/6689743/9648503/fdf02362-521b-11e5-904a-14e8aee345ae.gif)
for non-retina
